#pragma once

enum eMsgID
{
	MSGID_TITLESCENE_TITLE,
	MSGID_TITLESCENE_DESCRIPTION,
	MSGID_ACCOUNTSCENE_TITLE,
	MSGID_ACTIONSCENE_TITLE,
	MSGID_CONFIRMSCENE_TITLE,
	MSGID_CONFIRMSCENE_DESCRIPTION,
	MSGID_DEBUGSCENE_TITLE,
	MSGID_SUCCESS,
	MSGID_FAIL,
	MSGID_BACKUP,
	MSGID_RESTORE,
	MSGID_REMOVE,
	MSGID_BACK,


	MSGID_MAX,
};
